# Base configs
baseurl: "https://florisherman.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Floris van Schouwenburg"
subtitle: "Photos through my lens!"
author: "Floris van Schouwenburg"
header:
 title: "Photography"
 subtitle: "by Floris van Schouwenburg"
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a profesional sports photographer from namibia."
 github: ""
web_design: "Floris"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/florisherman"
  instagram: "https://www.instagram.com/florisherman"
  dribbble: "https://dribbble.com/florisherman"
  linkedin: "https://in.linkedin.com/in/florisherman"
  github: "https://www.github.com/florisherman"
